version: '3.8'
services:
  clearinghouse:
    build: ./core-services/clearinghouse
    image: clearinghouse
    ports:
      - "2402:2402"
      - "2403:2403"
    depends_on: 
      - db
      - rabbitmq-setup
    networks:
      - exchange-network
    volumes:
      - ./logs:/app/logs

  market-data-feed:
    build: ./core-services/market-data-feed
    image: market-data-feed
    ports:
      - "2404:2404"
    depends_on: 
      - db
      - rabbitmq-setup
    networks:
      - exchange-network
    volumes:
      - ./logs:/app/logs

  matching-engine:
    build: ./core-services/matching-engine
    image: matching-engine
    ports:
      - "2401:2401"
    depends_on: 
      - rabbitmq-setup
    networks:
      - exchange-network
    volumes:
      - ./logs:/usr/src/app/logs

  order-entry-gateway:
    build: ./core-services/order-entry-gateway
    image: order-entry-gateway
    ports:
      - "2400:2400"
    depends_on: 
      - rabbitmq-setup
    networks:
      - exchange-network
    volumes:
      - ./logs:/usr/src/app/logs

  db:
    image: postgres
    volumes:
      - ./build/init_clearinghouse.sql:/docker-entrypoint-initdb.d/init_clearinghouse.sql
      - ./build/init_market_data.sql:/docker-entrypoint-initdb.d/init_market_data.sql
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5500:5432"
    networks:
      - exchange-network

  rabbitmq:
    build: 
      context: ./build
      dockerfile: Dockerfile.rabbitmq
    image: rabbitmq
    ports:
      - "5700:5672"
      - "15700:15672"
    networks:
      - exchange-network

  rabbitmq-setup:
    build: 
      context: ./build
      dockerfile: Dockerfile.rabbitmq-setup
    image: rabbitmq-setup
    command: /bin/bash -c "/app/setup_rabbitmq.sh"
    depends_on: 
      - rabbitmq
    networks:
      - exchange-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - exchange-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - exchange-network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.2
    volumes:
      - ./logs/logstash-config/:/usr/share/logstash/pipeline/
      - ./logs/:/usr/share/logstash/logs
    depends_on:
      - elasticsearch
    ports:
      - "5000:5000"
    networks:
      - exchange-network
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
networks:
  exchange-network:
    driver: bridge
